version: 2
updates:
  - package-ecosystem: elm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ccamel
    reviewers:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: elm
    directory: "/review"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ccamel
    reviewers:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    assignees:
      - ccamel
    reviewers:
      - ccamel
    commit-message:
      prefix: ":arrow_up:"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    assignees:
      - ccamel
    reviewers:
      - ccamel
